GENERATED	:= silverlight4-license.txt silverlight4-privacy.txt silverlight5-license.txt silverlight5-privacy.txt

.PHONY: all clean
all: $(GENERATED)

clean:
	rm -f $(GENERATED)

silverlight4-license.txt:
	echo "            SOURCE: http://go2.microsoft.com/fwlink/?LinkID=183382" 						>  silverlight4-license.txt
	echo ""																							>> silverlight4-license.txt
	echo "License extracted from the website, date: $$(date -R)"									>> silverlight4-license.txt
	echo "_______________________________________________________________________________" 			>> silverlight4-license.txt
	echo ""																							>> silverlight4-license.txt
	w3m "http://www.microsoft.com/getsilverlight/locale/en-us/html/license_4.0.50401.html" -dump 	>> silverlight4-license.txt

silverlight4-privacy.txt:
	echo "            SOURCE: http://go2.microsoft.com/fwlink/?LinkID=200620" 						>  silverlight4-privacy.txt
	echo ""																							>> silverlight4-privacy.txt
	echo "License extracted from the website, date: $$(date -R)"									>> silverlight4-privacy.txt
	echo "_______________________________________________________________________________" 			>> silverlight4-privacy.txt
	echo ""																							>> silverlight4-privacy.txt
	w3m "http://www.microsoft.com/getsilverlight/locale/en-us/html/privacy_4.0.60531.html" -dump 	>> silverlight4-privacy.txt

silverlight5-license.txt:
	echo "             SOURCE: http://go.microsoft.com/fwlink/?LinkId=229303" 						>  silverlight5-license.txt
	echo ""																							>> silverlight5-license.txt
	echo "License extracted from the website, date: $$(date -R)"									>> silverlight5-license.txt
	echo "_______________________________________________________________________________" 			>> silverlight5-license.txt
	echo ""																							>> silverlight5-license.txt
	w3m "http://www.microsoft.com/getsilverlight/locale/en-us/html/license_5.0.61118.html" -dump 	>> silverlight5-license.txt

silverlight5-privacy.txt:
	echo "             SOURCE: http://go.microsoft.com/fwlink/?LinkId=229306" 						>  silverlight5-privacy.txt
	echo ""																							>> silverlight5-privacy.txt
	echo "License extracted from the website, date: $$(date -R)"									>> silverlight5-privacy.txt
	echo "_______________________________________________________________________________" 			>> silverlight5-privacy.txt
	echo ""																							>> silverlight5-privacy.txt
	w3m "http://www.microsoft.com/getsilverlight/locale/en-us/html/privacy_5.0.61118.html" -dump 	>> silverlight5-privacy.txt
