#!/bin/sh -e
#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

db_get pipelight/system-wide-installation
if [ "$RET" = "true" ]; then
	if [ ! -h "/usr/lib/mozilla/plugins/libpipelight.so" ]; then
		ln -s /usr/lib/pipelight/libpipelight.so /usr/lib/mozilla/plugins/libpipelight.so
	fi
else
	if [ -h "/usr/lib/mozilla/plugins/libpipelight.so" ]; then
		rm -f "/usr/lib/mozilla/plugins/libpipelight.so"
	fi
fi